version: '3.8'

services:
  backend:
    build: ./backend
    container_name: tic-tac-toe-backend
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build: ./frontend
    container_name: tic-tac-toe-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8000
